import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Moon from "./components/vectors/Moon";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${poppins.className} antialiased text-[#022932] flex flex-col justify-between`}
            >
                <header className='flex items-center relative py-10'>
                    <button className='absolute left-10'>
                        <Moon size={37} />
                    </button>
                    <nav className='flex gap-x-12 grow absolute left-1/2 -translate-x-1/2'>
                        <ul className='flex gap-x-5 font-medium'>
                            <li>
                                <a href='/home'>Home</a>
                            </li>
                        </ul>
                        <ul className='flex gap-x-5 font-medium'>
                            <li>
                                <a href='/the-science'>The science</a>
                            </li>
                        </ul>
                        <ul className='flex gap-x-5 font-medium'>
                            <li>
                                <a href='/alternatives'>Alternatives</a>
                            </li>
                        </ul>
                        <ul className='flex gap-x-5 font-medium'>
                            <li>
                                <a href='/about'>About us</a>
                            </li>
                        </ul>
                    </nav>
                    <h1 className='text-lg font-medium absolute right-10'>
                        Boxed Breathing Timer
                    </h1>
                </header>
                <main className="grow">{children}</main>

                <footer className='bg-[#033132] h-52'></footer>
            </body>
        </html>
    );
}
