import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Moon from "./components/vectors/Moon";


const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} antialiased text-[#022932] relative`}
			>
				<header className="flex items-center relative h-18">
					<button className="absolute left-10">
						<Moon size={37} />
					</button>
					<nav className="flex gap-x-12 grow absolute left-1/2 -translate-x-1/2  text-sm">
						<ul className="flex gap-x-8 font-medium">
							<li>
								<a href="/home">Home</a>
							</li>
						</ul>
						<ul className="flex gap-x-5 font-medium">
							<li>
								<a href="/the-science">The science</a>
							</li>
						</ul>
						<ul className="flex gap-x-5 font-medium">
							<li>
								<a href="/alternatives">Alternatives</a>
							</li>
						</ul>
						<ul className="flex gap-x-5 font-medium">
							<li>
								<a href="/about">About us</a>
							</li>
						</ul>
					</nav>
					<h1 className=" font-medium absolute right-10">
						Boxed Breathing Timer
					</h1>
				</header>
				<main>{children}</main>

				<footer className="bg-[#033132] h-32 w-full -bottom-32 absolute"></footer>
			</body>
		</html>
	);
}
