import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Moon from "./components/vectors/Moon";
import DarkModeSwitchButton from "./components/DarkModeSwitchButton";

const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} antialiased bg-surface text-onSurface relative`}
			>
				<header className="flex items-center relative h-18">
					<DarkModeSwitchButton />
					<nav className="flex gap-x-12 grow absolute left-1/2 -translate-x-1/2 text-[13.5px] [&_a]:font-medium dark:[&_a]:font-normal [&_a]:uppercase [&_a]:tracking-wider">
						<ul className="flex gap-x-8">
							<li>
								<a href="/home">Home</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a href="/the-science">The science</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a href="/alternatives">Alternatives</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a
									href="https://paypal.me/mehdicharife"
									target="_blank"
									rel="noopener noreferrer"
								>
									Support us
								</a>
							</li>
						</ul>
					</nav>
					<h1 className="font-medium absolute right-10">
						Boxed Breathing Timer
					</h1>
				</header>
				<main>{children}</main>

				<footer className="bg-footer text-onFooter h-32 w-full -bottom-32 absolute flex justify-between px-10 items-center">
					<div>
						<a
							href="/home"
							className="font-medium block mb-1"
						>
							Boxed Breathing Timer
						</a>
						<p className="text-xs">Copyright @ 2026</p>
					</div>
					<nav className="flex gap-x-8 text-[13px]">
						<ul className="flex gap-x-8 ">
							<li>
								<a href="/home">Home</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a href="/the-science">The science</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a href="/alternatives">Alternatives</a>
							</li>
						</ul>
						<ul className="flex gap-x-5">
							<li>
								<a
									href="https://paypal.me/mehdicharife"
									target="_blank"
									rel="noopener noreferrer"
								>
									Support us
								</a>
							</li>
						</ul>
					</nav>
				</footer>
			</body>
		</html>
	);
}
